name = "ada_tahoe"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Adam Jasinski"]
maintainers = ["Adam Jasinski <zasewq242@gmail.com>"]
maintainers-logins = ["adezxc"]

executables = ["ada_tahoe"]
[[depends-on]]
utilada = "^2.6.0"
#[[pins]]
#utilada = { url = "https://gitlab.com/stcarrez/ada-util", commit="99ca46a12f0d542348262d67b613d58f0d14c7b5" }
